'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import PasswordField from '@/components/password-field';
import type {User} from '@/lib/auth';
export default function Account({user}:{user:User}){
 const [open,setOpen]=useState(false),[users,setUsers]=useState<User[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[code,setCode]=useState('');
 async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d=await r.json() as {error?:string;users?:User[];recoveryCode?:string};if(!r.ok)throw Error(d.error||'Ошибка запроса');return d}
 async function show(){setOpen(true);setError('');setNotice('');setCode('');if(user.role==='owner')try{setUsers((await request('/api/staff')).users||[])}catch(e){setError(String(e))}}
 async function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(action==='password'&&f.get('password')!==f.get('confirm')){setError('Новые пароли не совпадают.');return}setBusy(true);setError('');setNotice('');try{const result=await request(action==='create'?'/api/staff':'/api/auth',{action,name:f.get('name'),phone:f.get('phone'),password:f.get('password'),currentPassword:f.get('currentPassword')});form.reset();setCode(result.recoveryCode||'');setNotice(action==='create'?'Сотрудник добавлен.':action==='phone'?'Телефон сохранён. Теперь используйте его для входа.':action==='recovery-code'?'Сохраните код ниже. Предыдущий резервный код больше не действует.':'Пароль изменён. Входы на других устройствах завершены.');if(action==='create')setUsers((await request('/api/staff')).users||[])}catch(e){setError(e instanceof Error?e.message:'Ошибка запроса')}finally{setBusy(false)}}
 async function toggle(u:User){setBusy(true);setError('');try{await request('/api/staff',{action:'toggle',id:u.id,active:!u.active});setUsers((await request('/api/staff')).users||[])}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await request('/api/auth',{action:'logout'});window.location.assign('/login')}catch{setError('Не удалось выйти. Повторите попытку.');setOpen(true);setBusy(false)}}
 return <><div className="account-actions"><button onClick={show}>{user.name} · {user.role==='owner'?'Владелец':'Сотрудник'}</button><button disabled={busy} onClick={logout}>Выйти</button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="shop-dialog account-dialog"><DialogTitle>{user.role==='owner'?'Аккаунт и сотрудники':'Мой аккаунт'}</DialogTitle><DialogDescription>Телефон: {user.phone||'не привязан'}. Прежний логин: {user.username}</DialogDescription>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}{code&&<code className="recovery-code">{code}</code>}{user.role==='owner'&&<><h3>Сотрудники</h3><div className="staff-list">{users.map(u=><div key={u.id}><span><b>{u.name}</b><small>{u.phone||u.username} · {u.role==='owner'?'Владелец':u.active?'Доступ открыт':'Доступ отключён'}</small></span>{u.role!=='owner'&&<button disabled={busy} onClick={()=>toggle(u)}>{u.active?'Отключить':'Включить'}</button>}</div>)}</div><h3>Добавить сотрудника</h3><form onSubmit={e=>submit(e,'create')}><label>Имя<input name="name" required maxLength={80}/></label><label>Телефон<input name="phone" type="tel" required maxLength={30} placeholder="+996 555 123 456"/></label><PasswordField label="Пароль сотрудника" newPassword/><small>От 12 символов. Сотрудник сможет изменить пароль в своём аккаунте.</small><button className="primary" disabled={busy}>Добавить сотрудника</button></form></>}<h3>Телефон для входа</h3><form onSubmit={e=>submit(e,'phone')}><label>Ваш номер<input name="phone" type="tel" required maxLength={30} defaultValue={user.phone||''} placeholder="+996 555 123 456"/></label><PasswordField label="Текущий пароль" name="currentPassword"/><button disabled={busy}>Сохранить телефон</button></form><h3>Резервный код</h3><p>Позволяет восстановить вход без SMS. Сохраните код отдельно: он показывается только при создании и действует один раз.</p><form onSubmit={e=>submit(e,'recovery-code')}><PasswordField label="Текущий пароль" name="currentPassword"/><button disabled={busy}>Создать новый резервный код</button></form><h3>Изменить свой пароль</h3><form onSubmit={e=>submit(e,'password')}><PasswordField label="Текущий пароль" name="currentPassword"/><PasswordField label="Новый пароль" newPassword/><PasswordField label="Повторите новый пароль" name="confirm" newPassword/><button disabled={busy}>Изменить пароль</button></form></DialogContent></Dialog></>
}
