"use client";
import {useEffect,useState} from 'react';
import Account from './account';
import Reports from './reports';
import OperationForm from './operation-form';
import type {User} from '@/lib/auth';
import {Flower2,Plus,ArrowDownLeft,ShoppingBag,Package,BarChart3,Trash2,RefreshCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
type Product={id:string;name:string;category:string;stock:number;cost:number;price:number;minimum:number};
type Recipe={id:string;name:string;price:number;parts:{productId:string;quantity:number}[]};
type Data={products:Product[];recipes:Recipe[];documents:{id:string;created:number;kind:string;summary:string;amount:number;note:string;reversed_by:string|null}[];report:{revenue:number;cost:number;loss:number;expenses:number;sales:number}};
const money=(v:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(v/100)+' сом';
async function responseData(r:Response):Promise<Data & {error:string}>{if(!r.headers.get('content-type')?.includes('application/json'))throw Error('Не удалось связаться с магазином. Обновите страницу или повторите загрузку.');return r.json() as Promise<Data & {error:string}>;}
const kinds:Record<string,string>={sale:'Продажа',receipt:'Поступление',writeoff:'Списание',refund:'Возврат',cancel:'Отмена',expense:'Расход',inventory:'Инвентаризация','edit-product':'Изменение товара','edit-recipe':'Изменение букета'};
const empty:Data={products:[],recipes:[],documents:[],report:{revenue:0,cost:0,loss:0,expenses:0,sales:0}};
export default function Workspace({user}:{user:User}){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('stock'),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 const [name,setName]=useState(''),[category,setCategory]=useState('Цветы'),[price,setPrice]=useState(''),[minimum,setMinimum]=useState('5'),[note,setNote]=useState(''),[lines,setLines]=useState<{id:string;quantity:string;cost:string}[]>([]),[requestId,setRequestId]=useState('');
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/shop');const d=await responseData(r);if(!r.ok)throw Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить данные')}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:'read_inventory',description:'Read saved flower shop inventory and sales totals. Does not modify records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');const r=await fetch('/api/shop');const d=await responseData(r);if(!r.ok)throw Error(d.error);setData(d);return {products:d.products,report:d.report}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 function open(kind:string){setModal(kind);setFormError('');setName('');setPrice('');setMinimum('5');setCategory('Цветы');setNote('');setLines([{id:'',quantity:'1',cost:''}]);setRequestId(crypto.randomUUID())}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setFormError('');try{const body=modal==='product'?{kind:modal,id:requestId,name,category,price:Number(price),minimum:Number(minimum)}:modal==='recipe'?{kind:modal,id:requestId,name,price:Number(price),lines:lines.map(l=>({id:l.id,quantity:Number(l.quantity)}))}:{kind:modal,id:requestId,note,lines:lines.map(l=>({id:l.id,quantity:Number(l.quantity),cost:Number(l.cost)}))};const r=await fetch('/api/shop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await responseData(r);if(!r.ok)throw Error(d.error);setModal('');setNotice('Сохранено. Остатки обновлены.');await refresh()}catch(e){setFormError(e instanceof Error?e.message:'Не удалось сохранить')}finally{setBusy(false)}}
 const stockValue=data.products.reduce((s,p)=>s+p.stock*p.cost,0),low=data.products.filter(p=>p.stock<=p.minimum);
 const options=[...data.products.map(p=>({id:p.id,label:p.name+' · '+p.stock+' шт.'})),...(modal==='sale'?data.recipes.map(r=>({id:r.id,label:'Букет · '+r.name})):[])];
 const recipeCost=(r:Recipe)=>r.parts.reduce((s,l)=>s+(data.products.find(p=>p.id===l.productId)?.cost||0)*l.quantity,0);
 return <><header className="topbar"><a className="brand" href="/"><Flower2 size={30}/><span>MAGNAT<span className="brand-small">FLOWER / УЧЁТ МАГАЗИНА</span></span></a><Account user={user}/></header><main><div className="heading"><div><div className="eyebrow">МАГАЗИН / ОБЗОР</div><h1>Склад и продажи</h1><p>Цветы, букеты и продажи — в одном месте.</p></div><button className="primary" onClick={()=>open('sale')}><Plus size={19}/>Новая продажа</button></div>
 <div className="stats"><article><span>Товары на складе</span><strong>{loading?'—':data.products.reduce((s,p)=>s+p.stock,0)}<small> шт.</small></strong><p>{data.products.length} наименований</p></article><article><span>Стоимость остатков</span><strong>{loading?'—':money(stockValue)}</strong><p>По средней закупочной цене</p></article><article><span>Выручка за всё время</span><strong>{loading?'—':money(data.report.revenue)}</strong><p>{data.report.sales} продаж</p></article><article className="attention"><span>Требуют пополнения</span><strong>{loading?'—':low.length}<small> позиций</small></strong><p>На уровне минимального остатка</p></article></div>
 {error&&<div className="alert" role="alert">{error}<button onClick={refresh}>Повторить загрузку</button></div>}{notice&&<div className="notice" role="status">{notice}<button aria-label="Закрыть уведомление" onClick={()=>setNotice('')}>×</button></div>}
 <Tabs value={tab} onValueChange={setTab}><div className="section-nav"><TabsList className="nav-tabs"><TabsTrigger value="stock"><Package/>Склад</TabsTrigger><TabsTrigger value="recipes"><Flower2/>Букеты</TabsTrigger><TabsTrigger value="history"><ShoppingBag/>Операции</TabsTrigger><TabsTrigger value="reports"><BarChart3/>Отчёты</TabsTrigger></TabsList><button className="icon-button" aria-label="Обновить данные" onClick={refresh} disabled={loading}><RefreshCw size={18}/></button></div>
 <TabsContent value="stock"><section className="panel"><div className="panel-head"><div><h2>Товары и остатки</h2><p>Цветы, зелень и упаковка</p></div><div className="actions"><OperationForm kind="inventory" products={data.products} label="Инвентаризация" onSaved={refresh}/><button onClick={()=>open('receipt')}><ArrowDownLeft size={17}/>Поступление</button><button onClick={()=>open('writeoff')}>Списание</button><button className="dark" onClick={()=>open('product')}><Plus size={17}/>Товар</button></div></div><Table><TableHeader><TableRow><TableHead>Наименование</TableHead><TableHead>Категория</TableHead><TableHead>Остаток</TableHead><TableHead>Закупочная</TableHead><TableHead>Розничная</TableHead><TableHead>Состояние</TableHead><TableHead>Действия</TableHead></TableRow></TableHeader><TableBody>{data.products.map(p=><TableRow key={p.id}><TableCell className="item-name">{p.name}</TableCell><TableCell>{p.category}</TableCell><TableCell>{p.stock} шт.</TableCell><TableCell>{money(p.cost)}</TableCell><TableCell>{money(p.price)}</TableCell><TableCell><span className={'badge '+(p.stock<=p.minimum?'warn':'')}>{p.stock===0?'Нет в наличии':p.stock<=p.minimum?'Пополнить':'В наличии'}</span></TableCell><TableCell><OperationForm kind="edit-product" product={p} products={data.products} label="Изменить" onSaved={refresh}/></TableCell></TableRow>)}</TableBody></Table>{!data.products.length&&<div className="empty"><Package size={36}/><h3>{loading?'Загружаем склад…':'Добавьте первый товар'}</h3><p>Создайте карточку цветка или упаковки, затем оформите поступление.</p><button onClick={()=>open('product')}>Добавить товар</button></div>}</section></TabsContent>
 <TabsContent value="recipes"><section className="panel"><div className="panel-head"><div><h2>Букеты</h2><p>Состав и себестоимость каждого букета</p></div><button className="dark" onClick={()=>open('recipe')}><Plus size={17}/>Создать букет</button></div><div className="recipe-grid">{data.recipes.map(r=><article className="recipe" key={r.id}><Flower2/><h3>{r.name}</h3><p>{r.parts.map(l=>`${data.products.find(p=>p.id===l.productId)?.name} × ${l.quantity}`).join(', ')}</p><div>Себестоимость <b>{money(recipeCost(r))}</b></div><div>Цена продажи <b>{money(r.price)}</b></div><OperationForm kind="edit-recipe" recipe={r} products={data.products} label="Изменить" onSaved={refresh}/></article>)}</div>{!data.recipes.length&&<div className="empty"><Flower2 size={36}/><h3>У каждого букета свой состав</h3><p>Добавьте товары на склад, затем соберите из них букет.</p></div>}</section></TabsContent>
 <TabsContent value="history"><section className="panel"><div className="panel-head"><div><h2>Журнал операций</h2><p>Последние 100 документов · отмены и возвраты сохраняются отдельно</p></div><OperationForm kind="expense" products={data.products} label="Добавить расход" onSaved={refresh}/></div><Table><TableHeader><TableRow><TableHead>Дата</TableHead><TableHead>Операция</TableHead><TableHead>Состав</TableHead><TableHead>Сумма</TableHead><TableHead>Комментарий</TableHead><TableHead>Действия</TableHead></TableRow></TableHeader><TableBody>{data.documents.map(d=><TableRow key={d.id}><TableCell>{new Date(d.created*1000).toLocaleString('ru-RU',{timeZone:'Asia/Bishkek'})}</TableCell><TableCell><span className={'badge '+(d.kind==='writeoff'?'warn':'')}>{kinds[d.kind]}</span></TableCell><TableCell>{d.summary}</TableCell><TableCell>{money(d.amount)}</TableCell><TableCell>{d.note||'—'}</TableCell><TableCell>{d.reversed_by?<span className="badge">Отменено / возвращено</span>:['sale','receipt','writeoff','inventory','expense'].includes(d.kind)&&<div className="history-actions">{d.kind==='sale'&&<OperationForm kind="refund" targetId={d.id} products={data.products} label="Возврат" onSaved={refresh}/>}<OperationForm kind="cancel" targetId={d.id} products={data.products} label="Отменить" onSaved={refresh}/></div>}</TableCell></TableRow>)}</TableBody></Table>{!data.documents.length&&<div className="empty"><ShoppingBag size={36}/><h3>Здесь появится история магазина</h3><p>Поступления, продажи и списания сохраняются автоматически.</p></div>}</section></TabsContent>
 <TabsContent value="reports"><Reports/></TabsContent></Tabs>
 <footer><span>Magnat Flower</span><span>Один магазин. Каждый цветок на учёте.</span></footer></main>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="shop-dialog"><DialogTitle>{modal==='product'?'Новый товар':modal==='recipe'?'Новый букет':kinds[modal]}</DialogTitle><DialogDescription>{modal==='product'?'Создайте карточку. Остаток добавляется через поступление.':modal==='recipe'?'Состав будет списываться со склада при продаже.':'Проверьте состав перед сохранением. Документ изменит остатки.'}</DialogDescription><form onSubmit={save}>{(modal==='product'||modal==='recipe')&&<><label>Название<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder={modal==='product'?'Например, роза красная 60 см':'Например, 15 красных роз'}/></label><div className="form-grid"><label>Цена продажи, сом<input required type="number" min="0.01" max="10000000" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label>{modal==='product'&&<label>Минимальный остаток<input required type="number" min="0" max="100000" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label>}</div></>}
 {modal==='product'?<label>Категория<Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Цветы','Зелень','Упаковка','Аксессуары'].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label>:<><div className="line-label">{modal==='recipe'?'Состав букета':'Товары'}<span>Количество{modal==='receipt'?' / цена закупки':''}</span></div>{lines.map((l,i)=><div className="form-line" key={i}><Select value={l.id} onValueChange={id=>setLines(lines.map((v,j)=>i===j?{...v,id}:v))}><SelectTrigger aria-label={'Товар '+(i+1)}><SelectValue placeholder="Выберите товар"/></SelectTrigger><SelectContent>{options.map(p=><SelectItem key={p.id} value={p.id}>{p.label}</SelectItem>)}</SelectContent></Select><input aria-label={'Количество '+(i+1)} required type="number" min="1" max="100000" step="1" value={l.quantity} onChange={e=>setLines(lines.map((v,j)=>i===j?{...v,quantity:e.target.value}:v))}/>{modal==='receipt'&&<input aria-label={'Цена закупки '+(i+1)} placeholder="сом за шт." required type="number" min="0.01" max="10000000" step="0.01" value={l.cost} onChange={e=>setLines(lines.map((v,j)=>i===j?{...v,cost:e.target.value}:v))}/>}<button type="button" className="icon-button" disabled={lines.length===1} aria-label="Убрать строку" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div>)}<button type="button" className="add-line" disabled={lines.length>=30} onClick={()=>setLines([...lines,{id:'',quantity:'1',cost:''}])}>+ Добавить позицию</button>{modal!=='recipe'&&<label>{modal==='writeoff'?'Причина списания':'Комментарий / поставщик'}<input required={modal==='writeoff'} maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label>}{!options.length&&<p className="form-error">Сначала добавьте товар во вкладке «Склад».</p>}</>}
 {modal==='sale'&&<div className="total">К оплате<strong>{money(lines.reduce((s,l)=>s+(data.products.find(p=>p.id===l.id)?.price??data.recipes.find(r=>r.id===l.id)?.price??0)*(Number(l.quantity)||0),0))}</strong></div>}{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="primary submit" disabled={busy||!!error||(modal!=='product'&&!options.length)}>{busy?'Сохраняем…':modal==='sale'?'Оформить продажу':'Сохранить'}</button></form></DialogContent></Dialog></>
}






