'use client';
import {useState} from 'react';
import {Flower2,LockKeyhole} from 'lucide-react';
import PasswordField from '@/components/password-field';
export default function LoginForm({setup}:{setup:boolean}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[recover,setRecover]=useState(false),[code,setCode]=useState(''),[identifier,setIdentifier]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if((setup||recover)&&f.get('password')!==f.get('confirm')){setError('Пароли не совпадают.');return}setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:recover?'recover':setup?'setup':'login',username:f.get('username'),password:f.get('password'),name:f.get('name'),code:f.get('code')})});const d=await r.json() as {error?:string;recoveryCode?:string;identifier?:string};if(!r.ok)throw Error(d.error||'Не удалось войти');if(d.recoveryCode){setCode(d.recoveryCode);setIdentifier(d.identifier||'');setBusy(false)}else window.location.assign('/')}catch(e){setError(e instanceof Error?e.message:'Нет связи с сервером');setBusy(false)}}
 return <main className="login-page"><section className="login-card"><a className="brand" href="/"><Flower2 size={30}/><span>MAGNAT<span className="brand-small">FLOWER / УЧЁТ МАГАЗИНА</span></span></a><div className="login-icon"><LockKeyhole/></div>{code?<><h1>Сохраните резервный код</h1><p>Он позволит установить новый пароль, если вы его забудете. Код действует один раз.</p><code className="recovery-code">{code}</code><p>Для входа: <b>{identifier}</b></p><p className="login-help">Сохраните код в менеджере паролей или запишите и уберите в надёжное место. Прежний код больше не действует.</p><a className="primary login-link" href="/login">Код сохранён — перейти ко входу</a></>:<><h1>{recover?'Восстановить доступ':setup?'Создайте аккаунт владельца':'Вход в магазин'}</h1><p>{recover?'Введите сохранённый резервный код и задайте новый пароль.':setup?'Укажите имя, телефон и придумайте пароль.':'Войдите по телефону и паролю.'}</p><form onSubmit={submit}>{setup&&!recover&&<label>Ваше имя<input name="name" autoComplete="name" required maxLength={80}/></label>}{recover?<label>Резервный код<input name="code" required autoComplete="off" spellCheck={false} maxLength={60} placeholder="Код, сохранённый в вашем аккаунте"/></label>:<label>{setup?'Номер телефона':'Телефон или прежний логин'}<input name="username" autoComplete="username" autoCapitalize="none" spellCheck={false} required maxLength={40} placeholder="+996 555 123 456"/></label>}<PasswordField label={recover?'Новый пароль':'Пароль'} newPassword={setup||recover}/>{(setup||recover)&&<><small>От 12 символов — можно использовать длинную запоминающуюся фразу.</small><PasswordField label="Повторите пароль" name="confirm" newPassword/></>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Подождите…':recover?'Установить новый пароль':setup?'Создать аккаунт':'Войти'}</button></form>{!setup&&<button className="text-button" type="button" disabled={busy} onClick={()=>{setRecover(!recover);setError('')}}>{recover?'Вернуться ко входу':'Забыли логин или пароль?'}</button>}{recover?<p className="login-help">Нет резервного кода? Сотруднику поможет владелец, владельцу — администратор, обслуживающий сайт. Восстановление по SMS ещё не подключено.</p>:!setup&&<p className="login-help">Если телефон ещё не привязан, используйте прежний логин. Номер можно добавить в своём аккаунте.</p>}</>}</section></main>
}
